# Generated by Django 6.0.7 on 2026-07-19 04:40

import django.core.validators
import inventory.storage
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Luxury SUV', 'Luxury SUV'), ('Luxury Sedan', 'Luxury Sedan'), ('Electric SUV', 'Electric SUV'), ('Premium SUV', 'Premium SUV'), ('SUV', 'SUV'), ('Compact SUV', 'Compact SUV'), ('Performance Coupe', 'Performance Coupe'), ('Family SUV', 'Family SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup')], max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, storage=inventory.storage.VehicleImageStorage(), upload_to=inventory.models.vehicle_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'make', 'model'],
                'indexes': [models.Index(fields=['make'], name='inventory_v_make_67dce3_idx'), models.Index(fields=['model'], name='inventory_v_model_a2fdeb_idx'), models.Index(fields=['category'], name='inventory_v_categor_5989d1_idx'), models.Index(fields=['price'], name='inventory_v_price_88fa8c_idx')],
            },
        ),
    ]
